{% set name = "tensorflow-probability" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: 69b7510b38b2e48bcfb9ff570ef598d489e4f1bcbe13276f5dd91c878b8d56d1
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 1
  script:
    - bazel build :pip_pkg
    - mkdir tmp-pkg
    - ./bazel-bin/pip_pkg tmp-pkg
    - "{{ PYTHON }} -m pip install --upgrade --no-deps -vv tmp-pkg/*.whl"
    
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel 
  host:
    - python >=3.8
    - pip
    - absl-py
  run:
    - python >=3.8
    - tensorflow-base >=2.13.0, <2.14.0
    - jax >=0.4.14, <0.5.0
    - numpy >=1.13.3
    - absl-py
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree

test:
  imports:
    - tensorflow_probability
    - tensorflow_probability.substrates.jax

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbedada
    - oblute
    - rluria14
    - jonas-eschle
