{% set name = "tensorflow-probability" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/{{ version }}.tar.gz
  sha256: 1fe89e85fd053bf36e8645a5a1a53b729bc254cf1516bc224fcbd1e4ff50083a
  patches:
    - 0001-always-build-release.patch

build:
  # upstream explicitly builds per-OS wheels,
  # so maybe it's not actually noarch?
  number: 0
  script: 
    - bazel build :pip_pkg
    - mkdir tmp-pkg
    - ./bazel-bin/pip_pkg tmp-pkg
    - "{{ PYTHON }} -m pip install . --no-deps -vv tmp-pkg/*.whl"

requirements:
  host:
    - python
    - pip
    - bazel
  run:
    - python
    - tensorflow-base >=2,<3  # what is actual version needed?
    - numpy >=1.13.3
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
