{% set name = "tensorflow-probability" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: 8e6c151a90d83913a57bcca3d81ca1edea39318ddde4f42dc71105eabc45a819
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 0
  script:
    - rm -f BUILD
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.3
    - six >=1.10.0
    - decorator
    - cloudpickle >=0.6.1
    - tensorflow-base >=1.14.0

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
