{% set name = "tensorflow-probability" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: 1fe89e85fd053bf36e8645a5a1a53b729bc254cf1516bc224fcbd1e4ff50083a
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 0
  # The upstream directions say to use bazel, but this is
  # all bazel ends up doing. Since our bazel package has
  # glibc version issues on CI, just do things this way.
  script: 
    - rm -f BUILD
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    # NOTE: we definitely need tensorflow. but currently,
    #       we need a version that's unfortunately only in
    #       defaults, which seems to complicate things for CI.
    #       this package should still work if the user has a 
    #       working version of tensorflow available.
    - tensorflow-base >=2,<3  # what is actual version needed?
    - numpy >=1.13.3
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
