{% set name = "tensorflow-probability" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: b32d2ae211ec727df9791b501839619f5389134bd6d4fe951570f500b0e75f55
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 0
  # The upstream directions say to use bazel, but this is
  # all bazel ends up doing. Since our bazel package can have
  # glibc version issues on CI, just do things this way.
  script:
    - rm -f BUILD
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # NOTE: tf is currently pulled in from defaults,
    #       so we have flexible channel priority set
    #       in conda-forge.yml
    # tested and stable against TensorFlow version 2.10 and jax 0.3.17
    # https://github.com/tensorflow/probability/releases/tag/v0.18.0
    - tensorflow-base ~=2.10.0
    - jax ==0.3.17
    - numpy >=1.13.3
    - absl-py
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbedada
    - oblute
    - rluria14
    - jonas-eschle
