{% set name = "tensorflow-probability" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/py2.py3/t/tensorflow-probability/tensorflow_probability-{{ version }}-py2.py3-none-any.whl
  sha256: f3f4d6431656c0122906888afe1b67b4400e82bd7f254b45b92e6c5b84ea8e3e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation tensorflow_probability-{{ version }}-py2.py3-none-any.whl

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - absl-py
    - six >=1.10.0
    - numpy >=1.13.3
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree
    - tensorflow >=2.16.0
    # Required as TFP only supports Keras 2
    - tf-keras >=2.16
  run_constrained:
    - tensorflow-datasets >=2.2.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - tensorflow-datasets >=2.2.0
    - jax
    - jaxlib
  commands:
    - pip check
  imports:
    - tensorflow_probability
    - tensorflow_probability.substrates.jax
    - tensorflow_probability.substrates.numpy

about:
  home: https://pypi.org/project/tensorflow-probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow
  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbedada
    - oblute
    - rluria14
    - jonas-eschle
    - ehfd
