{% set name = "tensorflow-probability" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: 73cf3e52d3b5ee48fc919631e7fa3621849b8ce8d453017016a5148815856bc2
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 0
  script:
    - bazel build :pip_pkg
    - mkdir tmp-pkg
    - ./bazel-bin/pip_pkg tmp-pkg
    - "{{ PYTHON }} -m pip install --upgrade --no-deps -vv tmp-pkg/*.whl"
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bazel <=6.5
  host:
    - python {{ python_min }}
    - pip
    - absl-py
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.13.3
    - absl-py
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree
  run_constrained:
    - tensorflow-base >=2.18.0, <2.19.0
    - tf-keras >=2.18  # required as TFP only supports Keras2, see  https://github.com/tensorflow/probability/blob/v0.24.0/setup.py#L51
    - jax >=0.4.35, <0.5.0

test:
  requires:
    - tf-keras
    - tensorflow-base
    - jax
    - python {{ python_min }}
  imports:
    - tensorflow_probability
    - tensorflow_probability.substrates.jax
    - tensorflow_probability.substrates.numpy

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow
  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbedada
    - oblute
    - rluria14
    - jonas-eschle
